"""Render bilingual level references from packaged metadata and actual examples."""

from __future__ import annotations

import argparse
from pathlib import Path

from namishu_arithmetic.catalog import describe_level, list_levels

ROOT = Path(__file__).resolve().parents[1]


def render(lang: str, descriptions: list[dict]) -> str:
    zh = lang == "zh-CN"
    lines = [
        "# 题型与级别目录" if zh else "# Series and level catalog",
        "",
        "<!-- Generated by scripts/build_catalog_docs.py. Do not edit by hand. -->",
        "",
        "[English](levels.md) · [简体中文](levels.zh-CN.md)",
        "",
        "编号标识预设题型，不对应年级，也不保证难度严格递增。例题使用 seed 42，由当前程序实际生成。"
        if zh
        else "Level IDs identify presets, not school grades or strictly increasing difficulty. "
        "Examples are generated by this version with seed 42.",
        "",
        "源范围不是答案范围；分数范围描述分子与分母。填空题的答案可能超出源范围或为负数、分数。"
        if zh
        else "Source ranges are not answer ranges. Fraction ranges describe numerators and denominators. "
        "Missing numbers may lie outside source ranges and can be negative or fractional.",
        "",
        "普通模式排除除零以及无解、多解填空。只有显式使用 `--allow-undefined` 才允许除零识别题；不保证每页出现。"
        if zh
        else "Normal mode excludes division by zero and blanks without a unique solution. "
        "`--allow-undefined` permits undefined-expression recognition tasks but does not guarantee one per page.",
        "",
    ]
    names = {
        "addsub": "加减法" if zh else "Addition and subtraction",
        "muldiv": "乘除法与四则混合" if zh else "Multiplication, division, and mixed operations",
        "fraction": "分数、小数与混合数字" if zh else "Fractions, decimals, and mixed numeric types",
    }
    for code, name in names.items():
        lines.extend([f"## {code}: {name}", ""])
        for item in descriptions:
            if item["series"] != code:
                continue
            lines.extend([f"- [{item['level']}. {item['title'][lang]}](#{code}-{item['level']})"])
        lines.append("")
    for item in descriptions:
        code, level = item["series"], item["level"]
        lines.extend(
            [
                f'<a id="{code}-{level}"></a>',
                "",
                f"## {code} {level}: {item['title'][lang]}",
                "",
                item["rules"][lang],
                "",
                f"- {'数字类型' if zh else 'Numeric types'}: {', '.join(item['operand_types'])}",
                f"- {'可能出现负操作数' if zh else 'Negative operands possible'}: {item['negative_operands_possible']}",
                f"- {'运算符' if zh else 'Operations'}: {' '.join(item['operators'])}",
                f"- {'填空' if zh else 'Missing number'}: {item['blank']}",
                f"- {'运算分组括号' if zh else 'Grouping parentheses'}: {item['parentheses']}",
                f"- {'默认每页题数' if zh else 'Default problems/page'}: {item['default_problems_per_page']}",
                "",
                "```text",
                *item["examples"],
                "```",
                "",
                "```bash",
                item["command"],
                "```",
                "",
            ]
        )
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    descriptions = [describe_level(item["series"], item["level"]) for item in list_levels()]
    for lang, filename in [("en", "levels.md"), ("zh-CN", "levels.zh-CN.md")]:
        path = ROOT / "docs" / filename
        content = render(lang, descriptions)
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                raise SystemExit(f"Stale catalog: run python scripts/build_catalog_docs.py ({filename})")
        else:
            path.write_text(content, encoding="utf-8")


if __name__ == "__main__":
    main()
