"""Render the English level reference from packaged metadata and actual examples."""

from __future__ import annotations

import argparse
from pathlib import Path

from namishu_arithmetic.catalog import describe_level, list_levels

ROOT = Path(__file__).resolve().parents[1]


def render(descriptions: list[dict]) -> str:
    lines = [
        "# Series and level catalog",
        "",
        "<!-- Generated by scripts/build_catalog_docs.py. Do not edit by hand. -->",
        "",
        "[English](levels.md) · [简体中文](levels.zh-CN.md)",
        "",
        "Level IDs identify presets, not school grades or strictly increasing difficulty. "
        "Examples are generated by this version with seed 42.",
        "",
        "Source ranges are not answer ranges. Fraction ranges describe numerators and denominators. "
        "Missing numbers may lie outside source ranges and can be negative or fractional.",
        "",
        "Zero denominators and divisors are allowed by default; "
        "use `--disallow-zero-denominator` to exclude them. "
        "Blanks always require a unique valid solution.",
        "",
    ]
    names = {
        "addsub": "Addition and subtraction",
        "muldiv": "Multiplication, division, and mixed operations",
        "fraction": "Fractions, decimals, and mixed numeric types",
    }
    for code, name in names.items():
        lines.extend([f"## {code}: {name}", ""])
        for item in descriptions:
            if item["series"] != code:
                continue
            lines.extend([f"- [{item['level']}. {item['title']}](#{code}-{item['level']})"])
        lines.append("")
    for item in descriptions:
        code, level = item["series"], item["level"]
        lines.extend(
            [
                f'<a id="{code}-{level}"></a>',
                "",
                f"## {code} {level}: {item['title']}",
                "",
                item["rules"],
                "",
                f"- Numeric types: {', '.join(item['operand_types'])}",
                f"- Negative operands possible: {item['negative_operands_possible']}",
                f"- Operations: {' '.join(item['operators'])}",
                f"- Missing number: {item['blank']}",
                f"- Grouping parentheses: {item['parentheses']}",
                f"- Default problems/page: {item['default_problems_per_page']}",
                "",
                "```text",
                *item["examples"],
                "```",
                "",
                "```bash",
                item["command"],
                "```",
                "",
            ]
        )
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    descriptions = [describe_level(item["series"], item["level"]) for item in list_levels()]
    path = ROOT / "docs" / "levels.md"
    content = render(descriptions)
    if args.check:
        if not path.exists() or path.read_text(encoding="utf-8") != content:
            raise SystemExit("Stale catalog: run python scripts/build_catalog_docs.py (levels.md)")
    else:
        path.write_text(content, encoding="utf-8")


if __name__ == "__main__":
    main()
